-- Run inside BEGIN/ROLLBACK, after pending migrations. Creates only synthetic fixtures.
do $$
declare
 a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); owner_a uuid:=gen_random_uuid();
 worker uuid:=gen_random_uuid(); platform_user uuid:=gen_random_uuid();
 sa uuid:=gen_random_uuid(); sb uuid:=gen_random_uuid(); plan uuid;
 customer uuid:=gen_random_uuid(); wallet uuid:=gen_random_uuid();
 command uuid:=gen_random_uuid(); order_a uuid:=gen_random_uuid(); order_b uuid:=gen_random_uuid();
 request uuid:=gen_random_uuid(); expires date; denied boolean; result text; report jsonb; new_org uuid;
 invitation jsonb; revoked_invitation jsonb; reset_revision bigint; product_a uuid:=gen_random_uuid(); product_b uuid:=gen_random_uuid(); campaign uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email) values(owner_a,owner_a||'@example.invalid'),(worker,worker||'@example.invalid'),(platform_user,platform_user||'@example.invalid');
 update auth.users set email_confirmed_at=now() where id=worker;
 insert into public.platform_admins(user_id) values(platform_user);
 insert into public.organizations(id,name) values(a,'ROLLBACK A'),(b,'ROLLBACK B');
 select id into strict plan from public.plans where code='growth';
 insert into public.subscriptions(organization_id,plan_id,status,current_period_end) values(a,plan,'active',current_date+10),(b,plan,'active',current_date+10);
 insert into public.stores(id,organization_id,name,slug,currency,phone_whatsapp) values(sa,a,'ROLLBACK A',sa::text,'SAR',''),(sb,b,'ROLLBACK B',sb::text,'SAR','');
 insert into public.organization_members(organization_id,user_id,role) values(a,owner_a,'owner');
 insert into public.store_members(store_id,user_id,role) values(sa,owner_a,'admin'),(sa,worker,'kitchen');
 insert into public.loyalty_customers(id,organization_id,phone,name) values(customer,b,'+12025550199','ROLLBACK');
 insert into public.value_wallets(id,organization_id,kind,balance) values(wallet,a,'promotional_credit',10);
 insert into public.orders(id,store_id,customer_name,customer_phone,order_type,status,total_amount,payment_method)
 values(order_a,sa,'ROLLBACK','+12025550199','pickup','pending',10,'cash'),(order_b,sb,'ROLLBACK','+12025550199','pickup','pending',10,'cash');
 perform set_config('request.jwt.claim.sub',owner_a::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_a,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if public.store_subscription_summary(sa)->'plans'->>'code'<>'growth' then raise exception 'FAIL subscription summary'; end if;
 denied:=false;
 begin perform public.store_subscription_summary(sb); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL cross-store subscription summary'; end if;
 execute 'reset role';
 delete from public.organization_members where organization_id=a and user_id=owner_a;
 execute 'set local role authenticated';
 if exists(select 1 from public.subscriptions where organization_id=a) then raise exception 'FAIL store-only admin reads billing subscription'; end if;
 if public.store_subscription_summary(sa)->>'status' is distinct from 'active' then raise exception 'FAIL store-only admin summary'; end if;
 execute 'reset role';
 insert into public.organization_members(organization_id,user_id,role) values(a,owner_a,'owner');
 execute 'set local role authenticated';
 revoked_invitation:=public.create_staff_invitation(sa,worker||'@example.invalid','kitchen');
 perform public.revoke_staff_invitation((revoked_invitation->>'id')::uuid);
 perform public.revoke_staff_invitation((revoked_invitation->>'id')::uuid);
 invitation:=public.create_staff_invitation(sa,worker||'@example.invalid','kitchen');
 denied:=false;
 begin perform public.create_staff_invitation(sb,worker||'@example.invalid','admin'); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL cross-tenant invitation RPC'; end if;
 if exists(select 1 from public.loyalty_customers where id=customer) then raise exception 'FAIL cross-tenant customer read'; end if;
 if exists(select 1 from public.orders where id=order_b) then raise exception 'FAIL cross-tenant order read'; end if;
 denied:=false;
 begin update public.loyalty_customers set points_balance=999 where id=customer; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL balance grant'; end if;
 denied:=false;
 begin update public.value_wallets set balance=999 where id=wallet; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL wallet grant'; end if;
 denied:=false;
 begin insert into public.staff_invitations(organization_id,store_id,email,role) values(a,sb,'nobody@example.invalid','admin'); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL invitation grant'; end if;
 if public.apply_wallet_entry(wallet,-5,'redeem','test',request::text)<>5 then raise exception 'FAIL wallet debit'; end if;
 if public.apply_wallet_entry(wallet,-5,'redeem','test',request::text)<>5 then raise exception 'FAIL wallet replay'; end if;
 denied:=false;
 begin perform public.apply_wallet_entry(wallet,-1,'redeem','test',request::text); exception when others then if sqlerrm='Idempotency conflict' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL wallet conflict'; end if;
 denied:=false;
 begin perform public.confirm_subscription_collection(a,gen_random_uuid(),'test',10,30); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL nonplatform collection'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',worker::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',worker,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 denied:=false;
 begin perform public.accept_staff_invitation(revoked_invitation->>'token'); exception when others then if sqlerrm='Invitation unavailable or email does not match' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL revoked invitation token after reinvite'; end if;
 denied:=false;
 begin perform public.revoke_staff_invitation((invitation->>'id')::uuid); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL kitchen invitation revocation'; end if;
 perform public.accept_staff_invitation(invitation->>'token');
 denied:=false;
 begin perform public.accept_staff_invitation(invitation->>'token'); exception when others then if sqlerrm='Invitation unavailable or email does not match' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL invitation replay'; end if;
 denied:=false;
 begin perform public.create_staff_invitation(sa,owner_a||'@example.invalid','admin'); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL kitchen role escalation'; end if;
 result:=public.kitchen_set_status(sa,order_a,'pending','preparing',command);
 if result<>'APPLIED' then raise exception 'FAIL command'; end if;
 if public.kitchen_set_status(sa,order_a,'pending','preparing',command)<>'APPLIED' then raise exception 'FAIL command replay'; end if;
 if public.kitchen_set_status(sa,order_a,'pending','cancelled',gen_random_uuid())<>'STALE' then raise exception 'FAIL stale command'; end if;
 denied:=false;
 begin perform public.kitchen_set_status(sb,order_b,'pending','preparing',gen_random_uuid()); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL cross-kitchen command'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',platform_user::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',platform_user,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 expires:=public.confirm_subscription_collection(a,request,request::text,100,30);
 if expires<>current_date+40 then raise exception 'FAIL paid period preservation'; end if;
 if public.confirm_subscription_collection(a,request,request::text,100,30)<>expires then raise exception 'FAIL collection replay'; end if;
 perform public.set_subscription_suspension(a,true);
 if public.subscription_current(a) then raise exception 'FAIL suspension'; end if;
 perform public.set_subscription_suspension(a,false);
 if not public.subscription_current(a) then raise exception 'FAIL reactivation'; end if;
 execute 'reset role';
 update public.subscriptions set current_period_end=current_date where organization_id=a;
 if public.subscription_current(a) then raise exception 'FAIL expiration boundary'; end if;
 if has_function_privilege('anon','public.reserve_limited_offer(uuid,integer)','execute') then raise exception 'FAIL public reservation'; end if;
 -- Reporting operates on completed orders only and subtracts recorded refunds.
 update public.orders set status='completed',refunded_amount=3,discount_amount=2 where id=order_a;
 report:=public.restaurant_sales_report(sa,now()-interval '1 hour',now()+interval '1 hour');
 if (report->>'net_sales')::numeric<>7 or (report->>'refunds')::numeric<>3 or (report->>'gross_known')::numeric<>12 then raise exception 'FAIL partial refund report: %',report; end if;
 update public.orders set refunded_amount=10 where id=order_a;
 if (public.restaurant_sales_report(sa,now()-interval '1 hour',now()+interval '1 hour')->>'net_sales')::numeric<>0 then raise exception 'FAIL full refund report'; end if;
 update public.orders set status='cancelled' where id=order_a;
 if (public.restaurant_sales_report(sa,now()-interval '1 hour',now()+interval '1 hour')->>'completed_orders')::integer<>0 then raise exception 'FAIL cancellation report'; end if;
 if (public.restaurant_sales_report(sa,now()+interval '1 hour',now()+interval '2 hour')->>'cancelled_orders')::integer<>0 then raise exception 'FAIL report date boundary'; end if;
 -- The onboarding transaction can be retried without duplicate organizations.
 request:=gen_random_uuid();
 new_org:=public.onboard_restaurant('ROLLBACK ONBOARD',request::text,'nobody@example.invalid','growth','',request,'ROLLBACK','Main');
 if public.onboard_restaurant('ROLLBACK ONBOARD',request::text,'nobody@example.invalid','growth','',request,'ROLLBACK','Main')<>new_org then raise exception 'FAIL onboarding replay'; end if;
 if not exists(select 1 from public.stores where organization_id=new_org) or not public.subscription_current(new_org) then raise exception 'FAIL onboarding transaction'; end if;
 if has_function_privilege('authenticated','public.activate_managed_account(uuid)','execute') then raise exception 'FAIL owner setup grant'; end if;
 insert into public.staff_accounts(user_id,store_id,username,role,intended_owner) values(owner_a,sa,'fixtureowner','admin',true);
 delete from public.organization_members where organization_id=a and user_id=owner_a;
 perform public.activate_managed_account(owner_a);
 if not exists(select 1 from public.organization_members where organization_id=a and user_id=owner_a and role='owner') then raise exception 'FAIL owner provisioning'; end if;
 perform public.revoke_managed_account(owner_a,sa);
 if exists(select 1 from public.organization_members where organization_id=a and user_id=owner_a) or exists(select 1 from public.store_members where store_id=sa and user_id=owner_a) then raise exception 'FAIL owner revocation'; end if;
 reset_revision:=public.begin_managed_account_reset(owner_a,sa);
 perform public.revoke_managed_account(owner_a,sa);
 if public.finish_managed_account_reset(owner_a,sa,reset_revision) then raise exception 'FAIL stale reset undoes disable'; end if;
 if not (select disabled from public.staff_accounts where user_id=owner_a) then raise exception 'FAIL disabled account reopened'; end if;
 reset_revision:=public.begin_managed_account_reset(owner_a,sa);
 if not public.finish_managed_account_reset(owner_a,sa,reset_revision) then raise exception 'FAIL current reset completion'; end if;
 if public.finish_managed_account_reset(owner_a,sa,reset_revision) then raise exception 'FAIL reset completion replay'; end if;
 if exists(select 1 from public.store_members where store_id=sa and user_id=owner_a) then raise exception 'FAIL reset grants membership before activation'; end if;
 if has_function_privilege('authenticated','public.finish_managed_account_reset(uuid,uuid,bigint)','execute') then raise exception 'FAIL reset completion public grant'; end if;
 denied:=false;
 begin perform public.activate_managed_account_revision(owner_a,reset_revision-1); exception when others then if sqlerrm='Account unavailable' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL stale activation after completed reset'; end if;
 perform public.activate_managed_account_revision(owner_a,reset_revision);
 perform public.activate_managed_account_revision(owner_a,reset_revision);
 if (select count(*) from public.store_members where store_id=sa and user_id=owner_a)<>1 then raise exception 'FAIL activation retry'; end if;
 perform public.revoke_managed_account(owner_a,sa);
 denied:=false;
 begin perform public.activate_managed_account_revision(owner_a,reset_revision); exception when others then if sqlerrm='Account unavailable' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL activation after disable'; end if;
 if exists(select 1 from public.organization_members where organization_id=a and user_id=owner_a) then raise exception 'FAIL disabled owner membership'; end if;
 if has_function_privilege('authenticated','public.activate_managed_account_revision(uuid,bigint)','execute') then raise exception 'FAIL versioned activation grant'; end if;
 -- Keep the same JWT subject before/after revocation: stale sessions lose DB access.
 insert into public.staff_accounts(user_id,store_id,username,role) values(worker,sa,'fixturekitchen','kitchen');
 update public.subscriptions set current_period_end=current_date+10 where organization_id=a;
 perform set_config('request.jwt.claim.sub',worker::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',worker,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if not exists(select 1 from public.orders where id=order_a) then raise exception 'FAIL kitchen baseline read'; end if;
 execute 'reset role';
 perform public.revoke_managed_account(worker,sa);
 execute 'set local role authenticated';
 if exists(select 1 from public.orders where id=order_a) then raise exception 'FAIL stale kitchen session reads orders'; end if;
 denied:=false;
 begin perform public.kitchen_set_status(sa,order_a,'cancelled','pending',gen_random_uuid()); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL stale kitchen session writes orders'; end if;
 execute 'reset role';
 reset_revision:=public.begin_managed_account_reset(worker,sa);
 if not public.finish_managed_account_reset(worker,sa,reset_revision) then raise exception 'FAIL kitchen reset'; end if;
 execute 'set local role authenticated';
 if exists(select 1 from public.orders where id=order_a) then raise exception 'FAIL reset alone restores kitchen access'; end if;
 execute 'reset role';
 perform public.activate_managed_account_revision(worker,reset_revision);
 perform public.change_managed_account_role(worker,sa,'admin');
 execute 'set local role authenticated';
 if public.store_subscription_summary(sa)->>'status' is distinct from 'active' then raise exception 'FAIL promoted admin access'; end if;
 execute 'reset role';
 perform public.change_managed_account_role(worker,sa,'kitchen');
 execute 'set local role authenticated';
 if not exists(select 1 from public.orders where id=order_a) then raise exception 'FAIL kitchen reactivation read'; end if;
 denied:=false;
 begin perform public.store_subscription_summary(sa); exception when others then if sqlerrm='Not authorized' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL reactivated kitchen elevated to admin'; end if;
 execute 'reset role';
 if exists(select 1 from public.organization_members where organization_id=a and user_id=worker) then raise exception 'FAIL kitchen organization escalation'; end if;
 insert into public.products(id,store_id,name,price) values(product_a,sa,'ROLLBACK A',10),(product_b,sb,'ROLLBACK B',10);
 insert into public.campaigns(id,store_id,name,slug,source,destination_product_id) values(campaign,sa,'ROLLBACK',campaign::text,'instagram',product_a);
 if (select destination_product_id from public.campaigns where id=campaign)<>product_a then raise exception 'FAIL saved campaign destination'; end if;
 denied:=false;
 begin update public.campaigns set destination_product_id=product_b where id=campaign; exception when others then denied:=true; end;
 if not denied then raise exception 'FAIL cross-store campaign product'; end if;
end $$;
