import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
export default function AcceptInvitation({token,storeSlug}) {
 const [user,setUser]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[destination,setDestination]=useState('');
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return ()=>subscription.unsubscribe();},[]);
 async function accept(){setBusy(true);try{const {data,error}=await supabase.rpc('accept_staff_invitation',{p_token:token});if(error)throw error;setMessage('تم قبول الدعوة وتفعيل صلاحيتك.');setDestination(data.role==='kitchen'?`/kitchen/${data.slug}`:`/admin/${data.slug}`);}catch{setMessage('تعذر قبول الدعوة. تأكد من استخدام البريد المدعو وأن الرابط لم تنتهِ صلاحيته.');}finally{setBusy(false);}}
 async function login(){setBusy(true); const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/s/${encodeURIComponent(storeSlug)}/loyalty?invite=${encodeURIComponent(token)}`,queryParams:{prompt:'select_account'}}});if(error)setMessage('تعذر بدء تسجيل الدخول');setBusy(false);}
 return <main dir="rtl" className="min-h-screen bg-background p-6 text-foreground"><section className="mx-auto max-w-md space-y-5 rounded-2xl border p-6"><h1 className="text-2xl font-bold">دعوة للانضمام إلى فريق المطعم</h1><p>سجّل الدخول بحساب Google المطابق للبريد الذي أرسل المدير الدعوة إليه.</p>{user?<><p dir="ltr">{user.email}</p><button disabled={busy||!!destination} onClick={accept} className="rounded-xl bg-primary p-3 text-primary-foreground">قبول الدعوة</button><button onClick={async()=>{await supabase.auth.signOut({scope:'local'});setUser(null);}} className="mr-3 underline">تغيير الحساب</button></>:<button disabled={busy} onClick={login} className="rounded-xl bg-primary p-3 text-primary-foreground">الدخول باستخدام Google</button>}<p role="status">{message}</p>{destination&&<a href={destination} className="block underline">فتح لوحة العمل</a>}</section></main>;
}
