create extension if not exists pgcrypto;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null,
  bio text, phone_whatsapp text not null, currency text not null default 'SAR', is_active boolean not null default true,
  logo_url text, cover_url text, timezone text not null default 'Asia/Riyadh', social_links jsonb not null default '{}'::jsonb, working_hours jsonb not null default '[]'::jsonb,
  appearance jsonb not null default '{}'::jsonb, settings jsonb not null default '{"acceptingOrders":true,"taxPercent":0,"minOrderValue":0}'::jsonb,
  payment jsonb not null default '{"currency":"SAR","cashOnDelivery":true}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.stores add column if not exists appearance jsonb not null default '{}'::jsonb;
alter table public.stores add column if not exists settings jsonb not null default '{"acceptingOrders":true,"taxPercent":0,"minOrderValue":0}'::jsonb;
alter table public.stores add column if not exists payment jsonb not null default '{"currency":"SAR","cashOnDelivery":true}'::jsonb;
alter table public.stores add column if not exists working_hours jsonb not null default '[]'::jsonb;
alter table public.stores add column if not exists timezone text not null default 'Asia/Riyadh';

create table if not exists public.store_members (
  store_id uuid not null references public.stores(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','kitchen')),
  created_at timestamptz not null default now(), primary key (store_id,user_id)
);
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade,
  name text not null, description text, display_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null, name text not null, description text, price numeric(12,2) not null check(price>=0),
  image_url text, tag text, is_available boolean not null default true, options jsonb not null default '[]'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade,
  title text not null, discount_percentage numeric(5,2) not null default 0 check(discount_percentage between 0 and 100), image_url text, active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.banners (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade,
  title text not null, subtitle text, image_url text not null, display_order integer not null default 0, active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.addons (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade,
  title text not null, price numeric(12,2) not null default 0 check(price>=0), image_url text, is_active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(), order_number bigint generated by default as identity,
  store_id uuid not null references public.stores(id) on delete restrict, customer_name text not null, customer_phone text not null,
  order_type text not null check(order_type in ('pickup','delivery')), delivery_address text, notes text, payment_method text not null default 'cash',
  subtotal_amount numeric(12,2) not null default 0, tax_amount numeric(12,2) not null default 0, total_amount numeric(12,2) not null,
  status text not null default 'pending' check(status in ('pending','preparing','ready','completed','cancelled')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null, product_name text not null, unit_price numeric(12,2) not null,
  quantity integer not null check(quantity between 1 and 100), selected_options jsonb not null default '[]'::jsonb
);
create index if not exists orders_store_status_created_idx on public.orders(store_id,status,created_at);
create index if not exists products_store_category_idx on public.products(store_id,category_id);

create or replace function public.is_store_member(target_store uuid, allowed_roles text[] default array['admin','kitchen'])
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.store_members m where m.store_id=target_store and m.user_id=auth.uid() and m.role=any(allowed_roles));
$$;

alter table public.stores enable row level security; alter table public.store_members enable row level security;
alter table public.categories enable row level security; alter table public.products enable row level security;
alter table public.offers enable row level security; alter table public.banners enable row level security; alter table public.addons enable row level security;
alter table public.orders enable row level security; alter table public.order_items enable row level security;

create policy "public reads active stores" on public.stores for select using (is_active or public.is_store_member(id));
create policy "admins update stores" on public.stores for update using (public.is_store_member(id,array['admin'])) with check (public.is_store_member(id,array['admin']));
create policy "members read own membership" on public.store_members for select using (user_id=auth.uid());
create policy "public reads active categories" on public.categories for select using (is_active and exists(select 1 from public.stores s where s.id=store_id and s.is_active));
create policy "public reads available products" on public.products for select using (is_available and exists(select 1 from public.stores s where s.id=store_id and s.is_active));
create policy "public reads active offers" on public.offers for select using (active and exists(select 1 from public.stores s where s.id=store_id and s.is_active));
create policy "public reads active banners" on public.banners for select using (active and exists(select 1 from public.stores s where s.id=store_id and s.is_active));
create policy "public reads active addons" on public.addons for select using (is_active and exists(select 1 from public.stores s where s.id=store_id and s.is_active));
create policy "admins manage categories" on public.categories for all using (public.is_store_member(store_id,array['admin'])) with check (public.is_store_member(store_id,array['admin']));
create policy "admins manage products" on public.products for all using (public.is_store_member(store_id,array['admin'])) with check (public.is_store_member(store_id,array['admin']));
create policy "admins manage offers" on public.offers for all using (public.is_store_member(store_id,array['admin'])) with check (public.is_store_member(store_id,array['admin']));
create policy "admins manage banners" on public.banners for all using (public.is_store_member(store_id,array['admin'])) with check (public.is_store_member(store_id,array['admin']));
create policy "admins manage addons" on public.addons for all using (public.is_store_member(store_id,array['admin'])) with check (public.is_store_member(store_id,array['admin']));
create policy "staff read orders" on public.orders for select using (public.is_store_member(store_id));
create policy "staff update orders" on public.orders for update using (public.is_store_member(store_id)) with check (public.is_store_member(store_id));
create policy "staff read order items" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and public.is_store_member(o.store_id)));

create or replace function public.create_order(
  p_store_id uuid, p_customer_name text, p_customer_phone text, p_order_type text, p_delivery_address text,
  p_notes text, p_payment_method text, p_items jsonb
) returns table(id uuid, order_number bigint, total_amount numeric)
language plpgsql security definer set search_path=public as $$
declare v_store public.stores; v_order_id uuid; v_subtotal numeric:=0; v_tax numeric:=0; v_item jsonb; v_product public.products; v_extra numeric:=0; v_qty integer; v_day jsonb; v_now_minutes integer; v_from integer; v_to integer;
begin
  select * into v_store from public.stores where stores.id=p_store_id and is_active for share;
  if not found or coalesce((v_store.settings->>'acceptingOrders')::boolean,true)=false then raise exception 'المطعم لا يستقبل طلبات حاليًا'; end if;
  if jsonb_array_length(coalesce(v_store.working_hours,'[]'::jsonb))>0 then
    select value into v_day from jsonb_array_elements(v_store.working_hours) where (value->>'id')::integer=extract(dow from now() at time zone v_store.timezone)::integer limit 1;
    if v_day is null or coalesce((v_day->>'isOpen')::boolean,false)=false then raise exception 'المطعم مغلق حاليًا'; end if;
    v_now_minutes:=extract(hour from now() at time zone v_store.timezone)::integer*60+extract(minute from now() at time zone v_store.timezone)::integer;
    v_from:=split_part(v_day->>'from',':',1)::integer*60+split_part(v_day->>'from',':',2)::integer;
    v_to:=split_part(v_day->>'to',':',1)::integer*60+split_part(v_day->>'to',':',2)::integer;
    if (v_from<=v_to and not(v_now_minutes between v_from and v_to)) or (v_from>v_to and not(v_now_minutes>=v_from or v_now_minutes<=v_to)) then raise exception 'المطعم مغلق حاليًا'; end if;
  end if;
  if p_order_type not in ('pickup','delivery') or (p_order_type='delivery' and nullif(trim(p_delivery_address),'') is null) then raise exception 'بيانات نوع الطلب غير مكتملة'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'السلة فارغة'; end if;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(100,coalesce((v_item->>'quantity')::integer,1)));
    select * into v_product from public.products where products.id=(v_item->>'product_id')::uuid and store_id=p_store_id and is_available;
    if not found then raise exception 'أحد الأصناف غير متاح'; end if;
    select coalesce(sum(coalesce(nullif(choice->>'extra_price','')::numeric,nullif(choice->>'price','')::numeric,0)),0) into v_extra
      from jsonb_array_elements(coalesce(v_product.options,'[]'::jsonb)) grp,
           jsonb_array_elements(coalesce(grp->'choices','[]'::jsonb)) choice
      where coalesce(choice->>'name',choice->>'label') in (select opt->>'name' from jsonb_array_elements(coalesce(v_item->'selected_options','[]'::jsonb)) opt);
    v_subtotal:=v_subtotal+((v_product.price+v_extra)*v_qty);
  end loop;
  if v_subtotal < coalesce((v_store.settings->>'minOrderValue')::numeric,0) then raise exception 'الطلب أقل من الحد الأدنى'; end if;
  v_tax:=round(v_subtotal*coalesce((v_store.settings->>'taxPercent')::numeric,0)/100,2);
  insert into public.orders(store_id,customer_name,customer_phone,order_type,delivery_address,notes,payment_method,subtotal_amount,tax_amount,total_amount)
    values(p_store_id,trim(p_customer_name),trim(p_customer_phone),p_order_type,nullif(trim(p_delivery_address),''),nullif(trim(p_notes),''),p_payment_method,v_subtotal,v_tax,v_subtotal+v_tax) returning orders.id into v_order_id;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(100,coalesce((v_item->>'quantity')::integer,1)));
    select * into v_product from public.products where products.id=(v_item->>'product_id')::uuid;
    select coalesce(sum(coalesce(nullif(choice->>'extra_price','')::numeric,nullif(choice->>'price','')::numeric,0)),0) into v_extra
      from jsonb_array_elements(coalesce(v_product.options,'[]'::jsonb)) grp, jsonb_array_elements(coalesce(grp->'choices','[]'::jsonb)) choice
      where coalesce(choice->>'name',choice->>'label') in (select opt->>'name' from jsonb_array_elements(coalesce(v_item->'selected_options','[]'::jsonb)) opt);
    insert into public.order_items(order_id,product_id,product_name,unit_price,quantity,selected_options) values(v_order_id,v_product.id,v_product.name,v_product.price+v_extra,v_qty,coalesce(v_item->'selected_options','[]'::jsonb));
  end loop;
  return query select o.id,o.order_number,o.total_amount from public.orders o where o.id=v_order_id;
end $$;
grant execute on function public.create_order(uuid,text,text,text,text,text,text,jsonb) to anon, authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('store-images','store-images',true,5242880,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "public reads store images" on storage.objects for select using (bucket_id='store-images');
create policy "admins upload store images" on storage.objects for insert to authenticated
  with check (bucket_id='store-images' and public.is_store_member((storage.foldername(name))[1]::uuid,array['admin']));
create policy "admins update store images" on storage.objects for update to authenticated
  using (bucket_id='store-images' and public.is_store_member((storage.foldername(name))[1]::uuid,array['admin']));
create policy "admins delete store images" on storage.objects for delete to authenticated
  using (bucket_id='store-images' and public.is_store_member((storage.foldername(name))[1]::uuid,array['admin']));

alter publication supabase_realtime add table public.orders;
alter publication supabase_realtime add table public.order_items;
